package com.project.chirp.convention

import com.android.build.api.dsl.LibraryExtension
import org.gradle.api.Project
import org.gradle.kotlin.dsl.configure
import org.jetbrains.kotlin.gradle.dsl.KotlinMultiplatformExtension

/**
 * **Header:** Centralizes the core Kotlin Multiplatform target definitions and compiler arguments specifically tailored for library modules.
 *
 * ## Strategy / Decisions
 * - **Distinct iOS Framework Naming:** Unlike the main application module (which compiles to a static `composeApp`), iOS frameworks generated by library modules need clear, distinct base names derived from the module path. This prevents binary collisions if they are consumed natively.
 * - **Dynamic vs. Static Frameworks:** The `isStatic` flag is intentionally omitted for these library targets, contrasting with the application module setup.
 * - **Global Opt-Ins:** Adds experimental compiler arguments (`expectActualClasses`, `RequiresOptIn`, `ExperimentalTime`) globally at the convention level. This prevents repetitive `@OptIn` annotations and compiler warnings from polluting the actual feature source code.
 *
 * ## How It Works
 * 1. Extends the Gradle `Project` to access and configure the Kotlin Multiplatform extension.
 * 2. Re-uses the iOS target configuration block, assigning the dynamically generated framework base name via `pathToFrameworkName()`.
 * 3. Appends specific `freeCompilerArgs` to the compiler options to bypass warnings for experimental KMP features and Kotlin Time APIs globally.
 *
 * ## Alternatives / Why Not
 * - **Configuring iOS targets uniformly for app and libraries:** We explicitly separated library configuration from application configuration because the main application needs static framework compilation, whereas libraries need unique dynamic framework generation.
 *
 * Technical Details
 * - The iOS target framework configuration dynamically dictates the output `.framework` binary name used by Xcode during native iOS compilation.
 */
internal fun Project.configureKotlinMultiplatform() {
    extensions.configure<LibraryExtension> {
        namespace = this@configureKotlinMultiplatform.pathToPackageName()
    }

    configureAndroidTarget()

    extensions.configure<KotlinMultiplatformExtension> {
        listOf(
            iosX64(),
            iosArm64(),
            iosSimulatorArm64()
        ).forEach { iosTarget ->
            iosTarget.binaries.framework {
                baseName = this@configureKotlinMultiplatform.pathToFrameworkName()
            }
        }

        compilerOptions {
            freeCompilerArgs.add("-Xexpect-actual-classes")
            freeCompilerArgs.add("-opt-in=kotlin.RequiresOptIn")
            freeCompilerArgs.add("-opt-in=kotlin.time.ExperimentalTime")
        }
    }
}
