package com.project.chat.data.network

import com.project.chat.domain.models.ConnectionState

/**
 * Expected interface for handling application-wide web socket and HTTP connection errors across platforms.
 *
 * ## Strategy / Decisions
 * Because Ktor uses completely different underlying network engines on Android (OkHttp) and iOS (Darwin),
 * the exceptions thrown during network failures (timeouts, hard disconnects) differ significantly.
 * This class abstracts the error handling logic so the shared data layer can observe application-wide
 * connection states and apply network retry mechanisms uniformly without platform-specific code leaking
 * into the business logic.
 *
 * ## How It Works
 * 1. Evaluates incoming exceptions via `getConnectionStateForError` to determine the resulting `ConnectionState`.
 * 2. Transforms exceptions via `transformException` before they hit the Flow operators.
 * 3. Determines if an exception represents a transient error that warrants a retry via `isRetryableError`.
 *
 * ## Alternatives / Why Not
 * Handling this purely in the common repository was avoided because extracting Darwin-specific errors
 * requires platform-specific imports (like `NSError`) that cannot be referenced in common Kotlin code.
 *
 * Technical Details:
 * Expected to be used in conjunction with Kotlin Flow `retry` operators and application UI state observers.
 *
 * Tags:
 * @param cause The underlying exception or throwable generated by the network client.
 * @return Returns a boolean indicating retry viability or a `ConnectionState` enum.
 */
expect class ConnectionErrorHandler {
    fun getConnectionStateForError(cause: Throwable): ConnectionState
    fun transformException(exception: Throwable): Throwable
    fun isRetriableError(cause: Throwable): Boolean
}
